iirt_message_homepage:
    path:     /message/index
    defaults: { _controller: IirtMessageBundle:message:index }
    
iirt_message_ajout:
    path:     /message/ajouter
    defaults: { _controller: IirtMessageBundle:message:ajouter }
