iirt_message_homepage:
    path:     /message/index
    defaults: { _controller: IirtMessageBundle:message:index }
    
iirt_message_ajout:
    path:     /message/ajouter/{destinataire}
    defaults: { _controller: IirtMessageBundle:message:ajouter }

iirt_message_afficherEns:
    path:     /message/new
    defaults: { _controller: IirtMessageBundle:message:afficherEns }
