<?php

namespace Iirt\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleRepository extends EntityRepository
{
}
