<?php

namespace Iirt\AnnouncementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncementFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementFileRepository extends EntityRepository
{
}
