<?php

namespace Iirt\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageFileRepository extends EntityRepository
{
}
